// <auto-generated />
namespace ToDoList.Lib.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class user_model_changes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(user_model_changes));
        
        string IMigrationMetadata.Id
        {
            get { return "201910301201320_user_model_changes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
